import {
  RiHomeLine,
  RiWallet3Line,
  RiKeyLine,
  RiKey2Line,
  RiBarChartLine,
  RiLayoutGridLine,
  RiLayout2Line,
  RiToggleLine,
  RiPieChartLine,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiArrowUpSLine,
  RiArrowDownSLine,
  RiCheckLine,
  RiSettings3Line,
  RiLogoutBoxLine,
  RiMoonLine,
  RiSunLine,
  RiRestartLine,
  RiUserLine,
  RiLineChartLine,
  RiMoneyDollarCircleLine,
  RiRidingLine,
} from "@remixicon/react";

export const iconMap = {
  RiHomeLine,
  RiWallet3Line,
  RiKeyLine,
  RiKey2Line,
  RiBarChartLine,
  RiLayoutGridLine,
  RiLayout2Line,
  RiToggleLine,
  RiPieChartLine,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiArrowUpSLine,
  RiArrowDownSLine,
  RiCheckLine,
  RiSettings3Line,
  RiLogoutBoxLine,
  RiMoonLine,
  RiSunLine,
  RiRestartLine,
  RiUserLine,
  RiLineChartLine,
  RiMoneyDollarCircleLine,
  RiRidingLine,
} as const;

export type IconName = keyof typeof iconMap;
